---
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD= #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN= #optional
      - DEFAULT_WORKSPACE=/home/matt/docker #optional
      - PWA_APPNAME=code-server #optional
    volumes:
      - /home/matt/docker/codeserver/config:/config
      - /home/matt:/home/matt
    ports:
      - 8443:8443
    restart: unless-stopped
