---
version: "2.1"
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vilnius
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - /home/matt/docker/calibre/config:/config
      - /mnt/samba_share/data/books:/config/Calibre Library
    ports:
      - 8080:8080
      - 8181:8181
      - 8081:8081
      - 9090:9090
    restart: unless-stopped
