services:
  samba:
    image: dockurr/samba
    container_name: samba
    environment:
      NAME: "Data"
      USER: "admin"
      PASS: "admin"
    ports:
      - 445:445
    volumes:
      - /mnt/samba_share:/storage
    restart: always
